name: CI

on:
  push:
    branches: [ main, ci-test ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: react-ui
        run: npm install

      - name: Build project
        working-directory: react-ui
        run: npm run build
