name: CI

on:
  push:
    branches: [main, ci-test]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: react-ui
        run: npm install

      - name: Build project
        working-directory: react-ui
        run: npm run build
